/**
 * Pure filename helper, deliberately kept out of the workbook module so it
 * carries no `server-only` marker and can be unit-tested directly.
 */

/**
 * Builds a filesystem- and Content-Disposition-safe download name, e.g.
 * "Offerta_Gomme_Rossi_SRL_2026-08-25_GR-260825-0042.xlsx". Accents are
 * folded rather than dropped so "Città" stays readable as "Citta".
 *
 * The reference is included so a folder of exports is sortable and each file
 * maps back to exactly one request. It is generated by us and already
 * matches [A-Z0-9-], but it is filtered anyway rather than trusted — this
 * value lands in a Content-Disposition header, where a stray quote or CRLF
 * would be a header-injection bug.
 */
export function safeFileName(companyName: string, createdAt: string, reference?: string): string {
  const company =
    companyName
      .normalize("NFD")
      // Strip combining accent marks (U+0300–U+036F).
      .replace(/[̀-ͯ]/g, "")
      .replace(/[^A-Za-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "")
      .slice(0, 60) || "Cliente";

  const date = new Date(createdAt);
  const iso = Number.isNaN(date.getTime())
    ? new Date().toISOString().slice(0, 10)
    : date.toISOString().slice(0, 10);

  const suffix = reference ? `_${reference.replace(/[^A-Za-z0-9-]+/g, "")}`.slice(0, 32) : "";
  return `Offerta_${company}_${iso}${suffix}.xlsx`;
}
