"use client";
import Link from "next/link";import {useEffect,useState} from "react";import {Button} from "@/components/Button";import {readBasket,writeBasket,type StoredBasketLine} from "@/lib/customer/basket";
type Preview={lines:{productId:string;oldDot:boolean;quantity:number;tyre:{brand:string|null;modelPattern:string|null;sizeDisplay:string|null};unitTyreNetCents:number|null;pfuStatus:string;unitVatCents:number|null;unitTotalCents:number|null}[];currency:string;tyreNetTotalCents:number;pfuTotalCents:number|null;vatTotalCents:number|null;grandTotalCents:number|null;monetaryStatus:string};
const money=(c:number|null)=>c===null?"Da confermare":new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR"}).format(c/100);
export function CustomerBasket(){
 const [stored,setStored]=useState<StoredBasketLine[]>([]),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState<string|null>(null);
 async function load(lines:StoredBasketLine[]){setStored(lines);if(!lines.length){setPreview(null);setBusy(false);return}setBusy(true);setError(null);try{const r=await fetch("/api/account/basket/preview",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({lines})});const j=await r.json();if(!r.ok)throw new Error(j.code);setPreview(j.basket);}catch{setError("Uno o più articoli non sono più disponibili. Aggiorna il carrello.");}finally{setBusy(false)}}
 useEffect(()=>{void load(readBasket())},[]);
 function quantity(line:StoredBasketLine,q:number){const next=stored.map(x=>x.productId===line.productId&&x.oldDot===line.oldDot?{...x,quantity:q}:x).filter(x=>x.quantity>0);writeBasket(next);void load(next)}
 if(busy)return <p className="text-sm text-ink-soft">Aggiornamento prezzi e disponibilità…</p>;
 if(!stored.length)return <div><h1 className="text-2xl font-extrabold text-ink">Carrello</h1><div className="mt-6 rounded-2xl bg-white p-8 text-center shadow-card"><p className="text-ink-soft">Il carrello è vuoto.</p><Link className="mt-4 inline-block font-semibold text-accent" href="/account/catalogue">Vai al catalogo</Link></div></div>;
 return <div><h1 className="text-2xl font-extrabold text-ink">Carrello</h1>{error&&<p className="mt-4 rounded-xl bg-state-danger-soft p-4 text-state-danger">{error}</p>}
 <div className="mt-6 space-y-3">{preview?.lines.map(line=>{const s=stored.find(x=>x.productId===line.productId&&x.oldDot===line.oldDot);if(!s)return null;return <div key={line.productId+"-"+line.oldDot} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-white p-5 shadow-card"><div><div className="font-bold">{line.tyre.brand} {line.tyre.modelPattern}</div><div className="text-sm text-ink-soft">{line.tyre.sizeDisplay}{line.oldDot?" · DOT precedente":""}</div></div><div className="flex items-center gap-3"><input aria-label="Quantità" className="h-10 w-20 rounded-lg border border-ink/15 px-2" type="number" min="1" max="100" value={line.quantity} onChange={e=>quantity(s,Math.max(0,Math.min(100,Number(e.target.value)||0)))}/><div className="w-28 text-right font-bold">{money(line.unitTyreNetCents===null?null:line.unitTyreNetCents*line.quantity)}</div><button className="text-sm text-ink-soft underline" onClick={()=>quantity(s,0)}>Rimuovi</button></div></div>})}</div>
 {preview&&<section className="mt-6 ml-auto max-w-md rounded-2xl bg-white p-5 shadow-card"><div className="flex justify-between"><span>Pneumatici netto</span><strong>{money(preview.tyreNetTotalCents)}</strong></div><div className="mt-2 flex justify-between"><span>PFU</span><strong>{money(preview.pfuTotalCents)}</strong></div><div className="mt-2 flex justify-between"><span>IVA</span><strong>{money(preview.vatTotalCents)}</strong></div><div className="mt-4 border-t pt-4 flex justify-between text-lg"><span>Totale</span><strong>{money(preview.grandTotalCents)}</strong></div>{preview.monetaryStatus!=="complete"&&<p className="mt-3 text-xs text-ink-soft">Il totale finale non è ancora disponibile perché PFU e relativo trattamento IVA devono essere confermati.</p>}<Button className="mt-5 w-full" disabled={preview.monetaryStatus!=="complete"} onClick={()=>{window.location.href="/account/checkout"}}>Procedi all'ordine</Button></section>}
 </div>;
}
