-- GommaRush baseline part 3/3: constraints, indexes, triggers, RLS, comments.
-- Parts 1 and 2 must be applied first (valid_client_offer_request_tyres
-- depends on is_valid_tyre_request()).
set search_path = "$user", public, extensions;

-- =========================== CONSTRAINTS =============================
alter table public.app_settings add constraint app_settings_pkey PRIMARY KEY (key);
alter table public.catalogue_conflicts add constraint catalogue_conflicts_pkey PRIMARY KEY (id);
alter table public.catalogue_import_rows add constraint catalogue_import_rows_pkey PRIMARY KEY (id);
alter table public.catalogue_import_runs add constraint catalogue_import_runs_pkey PRIMARY KEY (id);
alter table public.catalogue_products add constraint catalogue_products_pkey PRIMARY KEY (id);
alter table public.client_offer_requests add constraint client_offer_requests_pkey PRIMARY KEY (id);
alter table public.customer_locations add constraint customer_locations_pkey PRIMARY KEY (id);
alter table public.customers add constraint customers_pkey PRIMARY KEY (id);
alter table public.document_charges add constraint document_charges_pkey PRIMARY KEY (id);
alter table public.drivers add constraint drivers_pkey PRIMARY KEY (id);
alter table public.geocode_cache add constraint geocode_cache_pkey PRIMARY KEY (address_key);
alter table public.inventory_incidents add constraint inventory_incidents_pkey PRIMARY KEY (id);
alter table public.inventory_scans add constraint inventory_scans_pkey PRIMARY KEY (id);
alter table public.inventory_units add constraint inventory_units_pkey PRIMARY KEY (id);
alter table public.order_documents add constraint order_documents_pkey PRIMARY KEY (id);
alter table public.order_items add constraint order_items_pkey PRIMARY KEY (id);
alter table public.order_status_history add constraint order_status_history_pkey PRIMARY KEY (id);
alter table public.orders add constraint orders_pkey PRIMARY KEY (id);
alter table public.print_jobs add constraint print_jobs_pkey PRIMARY KEY (id);
alter table public.product_identifiers add constraint product_identifiers_pkey PRIMARY KEY (id);
alter table public.quote_request_events add constraint quote_request_events_pkey PRIMARY KEY (id);
alter table public.quote_request_items add constraint quote_request_items_pkey PRIMARY KEY (id);
alter table public.quote_request_reference_counter add constraint quote_request_reference_counter_pkey PRIMARY KEY (day);
alter table public.quote_request_webhook_events add constraint quote_request_webhook_events_pkey PRIMARY KEY (provider, event_id);
alter table public.quote_requests add constraint quote_requests_pkey PRIMARY KEY (id);
alter table public.supplier_customer_refs add constraint supplier_customer_refs_pkey PRIMARY KEY (id);
alter table public.supplier_listing_prices add constraint supplier_listing_prices_pkey PRIMARY KEY (id);
alter table public.supplier_locations add constraint supplier_locations_pkey PRIMARY KEY (id);
alter table public.supplier_product_listings add constraint supplier_product_listings_pkey PRIMARY KEY (id);
alter table public.suppliers add constraint suppliers_pkey PRIMARY KEY (id);
alter table public.vehicles add constraint vehicles_pkey PRIMARY KEY (id);
alter table public.warehouse_zones add constraint warehouse_zones_pkey PRIMARY KEY (id);
alter table public.catalogue_products add constraint catalogue_products_product_key_key UNIQUE (product_key);
alter table public.client_offer_requests add constraint client_offer_requests_idempotency_key_key UNIQUE (idempotency_key);
alter table public.client_offer_requests add constraint client_offer_requests_request_number_key UNIQUE (request_number);
alter table public.inventory_units add constraint inventory_units_order_item_id_unit_sequence_key UNIQUE (order_item_id, unit_sequence);
alter table public.inventory_units add constraint inventory_units_qr_token_key UNIQUE (qr_token);
alter table public.orders add constraint orders_order_number_key UNIQUE (order_number);
alter table public.orders add constraint orders_qr_token_key UNIQUE (qr_token);
alter table public.quote_requests add constraint quote_requests_request_number_key UNIQUE (request_number);
alter table public.supplier_customer_refs add constraint supplier_customer_refs_supplier_id_supplier_customer_code_key UNIQUE (supplier_id, supplier_customer_code);
alter table public.supplier_product_listings add constraint supplier_product_listings_supplier_listing_key_key UNIQUE (supplier_listing_key);
alter table public.warehouse_zones add constraint warehouse_zones_code_key UNIQUE (code);
alter table public.warehouse_zones add constraint warehouse_zones_qr_token_key UNIQUE (qr_token);
alter table public.catalogue_conflicts add constraint catalogue_conflicts_status_chk CHECK ((status = ANY (ARRAY['open'::text, 'resolved'::text, 'dismissed'::text])));
alter table public.catalogue_conflicts add constraint catalogue_conflicts_type_chk CHECK ((conflict_type = ANY (ARRAY['ean_spec_mismatch'::text, 'product_ean_change'::text, 'weight_conflict'::text, 'manufacturer_code_conflict'::text, 'ambiguous_match'::text, 'duplicate_source_row'::text])));
alter table public.catalogue_import_rows add constraint catalogue_import_rows_action_chk CHECK (((action IS NULL) OR (action = ANY (ARRAY['insert_product'::text, 'insert_listing'::text, 'update_listing'::text, 'unchanged'::text, 'conflict'::text, 'rejected'::text, 'deactivate_listing'::text]))));
alter table public.catalogue_import_rows add constraint catalogue_import_rows_validation_chk CHECK ((validation_result = ANY (ARRAY['pending'::text, 'valid'::text, 'review'::text, 'rejected'::text])));
alter table public.catalogue_import_runs add constraint catalogue_import_runs_mode_chk CHECK ((import_mode = ANY (ARRAY['complete'::text, 'partial'::text, 'manual_correction'::text])));
alter table public.catalogue_import_runs add constraint catalogue_import_runs_status_chk CHECK ((status = ANY (ARRAY['uploaded'::text, 'analyzing'::text, 'previewed'::text, 'committing'::text, 'committed'::text, 'failed'::text, 'cancelled'::text])));
alter table public.catalogue_products add constraint catalogue_products_dimensions_chk CHECK ((((width_mm IS NULL) OR (width_mm > 0)) AND ((aspect_ratio IS NULL) OR (aspect_ratio > 0)) AND ((rim_inch IS NULL) OR (rim_inch > 0))));
alter table public.catalogue_products add constraint catalogue_products_ean_status_chk CHECK ((ean_status = ANY (ARRAY['valid'::text, 'recovered_leading_zero'::text, 'invalid_check_digit'::text, 'missing'::text])));
alter table public.catalogue_products add constraint catalogue_products_scan_ready_chk CHECK (((scan_ready = false) OR ((ean IS NOT NULL) AND (ean_status = ANY (ARRAY['valid'::text, 'recovered_leading_zero'::text])))));
alter table public.catalogue_products add constraint catalogue_products_weight_positive_chk CHECK (((weight_kg IS NULL) OR (weight_kg > (0)::numeric)));
alter table public.catalogue_products add constraint catalogue_products_weight_provenance_chk CHECK (((weight_kg IS NULL) = (weight_status <> 'supplier_reported'::text)));
alter table public.catalogue_products add constraint catalogue_products_weight_status_chk CHECK ((weight_status = ANY (ARRAY['supplier_reported'::text, 'missing_or_zero'::text])));
alter table public.client_offer_requests add constraint client_offer_requests_contact_type_check CHECK ((contact_type = ANY (ARRAY['email'::text, 'phone'::text])));
alter table public.client_offer_requests add constraint client_offer_requests_delivery_preference_check CHECK ((delivery_preference = ANY (ARRAY['any'::text, '24_hours'::text, '48_hours'::text, '7_days'::text])));
alter table public.client_offer_requests add constraint client_offer_requests_notification_email_status_check CHECK ((notification_email_status = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text])));
alter table public.client_offer_requests add constraint client_offer_requests_status_check CHECK ((status = ANY (ARRAY['new'::text, 'reviewing'::text, 'quoted'::text, 'sent'::text, 'accepted'::text, 'rejected'::text, 'expired'::text, 'converted_to_order'::text, 'cancelled'::text])));
alter table public.client_offer_requests add constraint valid_client_offer_request_tyres CHECK (is_valid_tyre_request(tyres));
alter table public.document_charges add constraint document_charges_charge_type_check CHECK ((charge_type = ANY (ARRAY['PFU'::text, 'LOGISTICS_FEE'::text, 'TRANSPORT_FEE'::text, 'DISCOUNT'::text, 'VAT'::text, 'OTHER_FEE'::text])));
alter table public.inventory_incidents add constraint inventory_incidents_incident_type_check CHECK ((incident_type = ANY (ARRAY['customer_refusal'::text, 'damage'::text, 'defect'::text, 'disposed'::text, 'lost'::text, 'missing'::text, 'other'::text, 'quarantine'::text, 'return'::text, 'warranty'::text, 'wrong_delivery'::text, 'wrong_item'::text])));
alter table public.inventory_scans add constraint inventory_scans_result_chk CHECK ((result = ANY (ARRAY['success'::text, 'duplicate'::text, 'rejected'::text])));
alter table public.inventory_scans add constraint inventory_scans_scan_type_check CHECK ((scan_type = ANY (ARRAY['delivery'::text, 'found'::text, 'inventory_check'::text, 'loading'::text, 'manual_check'::text, 'manual_loading'::text, 'received'::text, 'return'::text, 'storage'::text, 'unloading'::text, 'zone_scan'::text])));
alter table public.inventory_units add constraint inventory_units_status_check CHECK ((status = ANY (ARRAY['expected'::text, 'received'::text, 'stored'::text, 'ready_for_loading'::text, 'loaded'::text, 'out_for_delivery'::text, 'delivered'::text, 'returned'::text, 'defective'::text, 'damaged'::text, 'missing'::text, 'lost'::text, 'quarantine'::text, 'disposed'::text])));
alter table public.inventory_units add constraint inventory_units_unit_type_check CHECK ((unit_type = ANY (ARRAY['tyre'::text, 'tube'::text, 'wheel'::text, 'accessory'::text, 'other'::text])));
alter table public.order_documents add constraint order_documents_extraction_status_check CHECK ((extraction_status = ANY (ARRAY['confirmed'::text, 'failed'::text, 'pending'::text, 'processing'::text, 'review_required'::text, 'unconfigured'::text])));
alter table public.order_documents add constraint order_documents_source_type_check CHECK ((source_type = ANY (ARRAY['pdf'::text, 'image'::text, 'manual'::text, 'email'::text])));
alter table public.order_items add constraint order_items_item_type_check CHECK ((item_type = ANY (ARRAY['tyre'::text, 'tube'::text, 'wheel'::text, 'accessory'::text, 'service'::text, 'fee'::text, 'other'::text])));
alter table public.order_items add constraint order_items_quantity_check CHECK ((quantity > 0));
alter table public.orders add constraint orders_payment_status_check CHECK ((payment_status = ANY (ARRAY['unknown'::text, 'not_required'::text, 'pending'::text, 'collected'::text, 'paid'::text, 'failed'::text])));
alter table public.orders add constraint orders_source_type_check CHECK ((source_type = ANY (ARRAY['pdf'::text, 'image'::text, 'manual'::text, 'email'::text])));
alter table public.orders add constraint orders_stand_code_chk CHECK (((stand_code IS NULL) OR (stand_code = ANY (ARRAY['A'::text, 'B'::text, 'C'::text, 'D'::text, 'E'::text]))));
alter table public.orders add constraint orders_status_check CHECK ((status = ANY (ARRAY['cancelled'::text, 'confirmed'::text, 'delivered'::text, 'draft'::text, 'expected'::text, 'loaded'::text, 'on_hold'::text, 'out_for_delivery'::text, 'partially_delivered'::text, 'partially_loaded'::text, 'partially_received'::text, 'ready_for_loading'::text, 'received'::text, 'returned'::text, 'review_required'::text, 'sorting'::text, 'stored'::text])));
alter table public.print_jobs add constraint print_jobs_print_type_check CHECK ((print_type = ANY (ARRAY['order_label'::text, 'inventory_unit_label'::text, 'zone_label'::text, 'return_label'::text, 'other'::text])));
alter table public.print_jobs add constraint print_jobs_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'printed'::text, 'failed'::text, 'cancelled'::text])));
alter table public.product_identifiers add constraint product_identifiers_type_chk CHECK ((identifier_type = ANY (ARRAY['ean'::text, 'gtin'::text, 'manufacturer_code'::text, 'supplier_article_code'::text])));
alter table public.product_identifiers add constraint product_identifiers_validation_chk CHECK ((validation_status = ANY (ARRAY['valid'::text, 'recovered_leading_zero'::text, 'invalid_check_digit'::text, 'unverified'::text])));
alter table public.quote_request_items add constraint quote_request_items_brand_present CHECK (((preference_type IS DISTINCT FROM 'specific_brand'::text) OR ((preferred_brand IS NOT NULL) AND (length(btrim(preferred_brand)) > 0))));
alter table public.quote_request_items add constraint quote_request_items_delivery_speed_check CHECK ((delivery_speed = ANY (ARRAY['48h'::text, '7d'::text])));
alter table public.quote_request_items add constraint quote_request_items_other_description CHECK (((product_type <> 'other'::text) OR ((description IS NOT NULL) AND (length(btrim(description)) > 0))));
alter table public.quote_request_items add constraint quote_request_items_preference_type_check CHECK (((preference_type IS NULL) OR (preference_type = ANY (ARRAY['best_price'::text, 'specific_brand'::text]))));
alter table public.quote_request_items add constraint quote_request_items_product_type_check CHECK ((product_type = ANY (ARRAY['tyre'::text, 'other'::text])));
alter table public.quote_request_items add constraint quote_request_items_profile_check CHECK (((profile IS NULL) OR ((profile >= 20) AND (profile <= 100))));
alter table public.quote_request_items add constraint quote_request_items_quantity_check CHECK (((quantity > 0) AND (quantity <= 1000)));
alter table public.quote_request_items add constraint quote_request_items_rim_check CHECK (((rim IS NULL) OR ((rim >= 10) AND (rim <= 30))));
alter table public.quote_request_items add constraint quote_request_items_season_check CHECK (((season IS NULL) OR (season = ANY (ARRAY['summer'::text, 'winter'::text, 'all_season'::text]))));
alter table public.quote_request_items add constraint quote_request_items_tyre_dimensions CHECK (((product_type <> 'tyre'::text) OR ((width IS NOT NULL) AND (profile IS NOT NULL) AND (rim IS NOT NULL))));
alter table public.quote_request_items add constraint quote_request_items_width_check CHECK (((width IS NULL) OR ((width >= 100) AND (width <= 500))));
alter table public.quote_requests add constraint quote_requests_company_name_check CHECK ((length(btrim(company_name)) > 0));
alter table public.quote_requests add constraint quote_requests_contact_email_check CHECK ((length(btrim(contact_email)) > 0));
alter table public.quote_requests add constraint quote_requests_delivery_preference_check CHECK (((delivery_preference IS NULL) OR (delivery_preference = ANY (ARRAY['48h'::text, '7d'::text]))));
alter table public.quote_requests add constraint quote_requests_language_check CHECK ((language = ANY (ARRAY['it'::text, 'en'::text])));
alter table public.quote_requests add constraint quote_requests_notification_status_check CHECK ((notification_status = ANY (ARRAY['pending'::text, 'sending'::text, 'sent'::text, 'delivered'::text, 'failed'::text])));
alter table public.quote_requests add constraint quote_requests_status_check CHECK ((status = ANY (ARRAY['submitted'::text, 'reviewing'::text, 'quote_preparing'::text, 'quote_ready'::text, 'sent'::text, 'accepted'::text, 'rejected'::text, 'expired'::text, 'archived'::text])));
alter table public.supplier_listing_prices add constraint supplier_listing_prices_price_chk CHECK (((purchase_price IS NULL) OR (purchase_price >= (0)::numeric)));
alter table public.vehicles add constraint vehicles_capacity_units_chk CHECK (((capacity_units IS NULL) OR (capacity_units > 0)));
alter table public.vehicles add constraint vehicles_color_key_chk CHECK (((color_key IS NULL) OR (color_key = ANY (ARRAY['blue'::text, 'purple'::text, 'teal'::text, 'indigo'::text, 'slate'::text, 'cyan'::text, 'rose'::text, 'amber'::text]))));
alter table public.warehouse_zones add constraint warehouse_zones_zone_type_check CHECK ((zone_type = ANY (ARRAY['sorting'::text, 'returns'::text, 'quarantine'::text, 'damaged'::text, 'loading'::text, 'storage'::text, 'other'::text])));
alter table public.catalogue_conflicts add constraint catalogue_conflicts_catalogue_product_id_fkey FOREIGN KEY (catalogue_product_id) REFERENCES catalogue_products(id) ON DELETE SET NULL;
alter table public.catalogue_conflicts add constraint catalogue_conflicts_competing_product_id_fkey FOREIGN KEY (competing_product_id) REFERENCES catalogue_products(id) ON DELETE SET NULL;
alter table public.catalogue_conflicts add constraint catalogue_conflicts_import_row_id_fkey FOREIGN KEY (import_row_id) REFERENCES catalogue_import_rows(id) ON DELETE SET NULL;
alter table public.catalogue_conflicts add constraint catalogue_conflicts_import_run_id_fkey FOREIGN KEY (import_run_id) REFERENCES catalogue_import_runs(id) ON DELETE SET NULL;
alter table public.catalogue_conflicts add constraint catalogue_conflicts_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL;
alter table public.catalogue_import_rows add constraint catalogue_import_rows_import_run_id_fkey FOREIGN KEY (import_run_id) REFERENCES catalogue_import_runs(id) ON DELETE CASCADE;
alter table public.catalogue_import_rows add constraint catalogue_import_rows_matched_listing_id_fkey FOREIGN KEY (matched_listing_id) REFERENCES supplier_product_listings(id) ON DELETE SET NULL;
alter table public.catalogue_import_rows add constraint catalogue_import_rows_matched_product_id_fkey FOREIGN KEY (matched_product_id) REFERENCES catalogue_products(id) ON DELETE SET NULL;
alter table public.catalogue_import_runs add constraint catalogue_import_runs_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT;
alter table public.customer_locations add constraint customer_locations_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;
alter table public.document_charges add constraint document_charges_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
alter table public.drivers add constraint drivers_current_vehicle_id_fkey FOREIGN KEY (current_vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL;
alter table public.inventory_incidents add constraint inventory_incidents_inventory_unit_id_fkey FOREIGN KEY (inventory_unit_id) REFERENCES inventory_units(id) ON DELETE CASCADE;
alter table public.inventory_incidents add constraint inventory_incidents_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
alter table public.inventory_scans add constraint inventory_scans_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE SET NULL;
alter table public.inventory_scans add constraint inventory_scans_inventory_unit_id_fkey FOREIGN KEY (inventory_unit_id) REFERENCES inventory_units(id) ON DELETE CASCADE;
alter table public.inventory_scans add constraint inventory_scans_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
alter table public.inventory_scans add constraint inventory_scans_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE SET NULL;
alter table public.inventory_scans add constraint inventory_scans_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL;
alter table public.inventory_scans add constraint inventory_scans_warehouse_zone_id_fkey FOREIGN KEY (warehouse_zone_id) REFERENCES warehouse_zones(id) ON DELETE SET NULL;
alter table public.inventory_units add constraint inventory_units_current_zone_id_fkey FOREIGN KEY (current_zone_id) REFERENCES warehouse_zones(id) ON DELETE SET NULL;
alter table public.inventory_units add constraint inventory_units_last_vehicle_id_fkey FOREIGN KEY (last_vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL;
alter table public.inventory_units add constraint inventory_units_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
alter table public.inventory_units add constraint inventory_units_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE;
alter table public.order_documents add constraint order_documents_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
alter table public.order_documents add constraint order_documents_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL;
alter table public.order_items add constraint order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
alter table public.order_status_history add constraint order_status_history_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
alter table public.orders add constraint orders_assigned_zone_id_fkey FOREIGN KEY (assigned_zone_id) REFERENCES warehouse_zones(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT;
alter table public.orders add constraint orders_customer_location_id_fkey FOREIGN KEY (customer_location_id) REFERENCES customer_locations(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES order_documents(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT;
alter table public.orders add constraint orders_supplier_location_id_fkey FOREIGN KEY (supplier_location_id) REFERENCES supplier_locations(id) ON DELETE SET NULL;
alter table public.orders add constraint orders_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL;
alter table public.print_jobs add constraint print_jobs_inventory_unit_id_fkey FOREIGN KEY (inventory_unit_id) REFERENCES inventory_units(id) ON DELETE CASCADE;
alter table public.print_jobs add constraint print_jobs_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
alter table public.product_identifiers add constraint product_identifiers_catalogue_product_id_fkey FOREIGN KEY (catalogue_product_id) REFERENCES catalogue_products(id) ON DELETE CASCADE;
alter table public.product_identifiers add constraint product_identifiers_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL;
alter table public.quote_request_events add constraint quote_request_events_quote_request_id_fkey FOREIGN KEY (quote_request_id) REFERENCES quote_requests(id) ON DELETE CASCADE;
alter table public.quote_request_items add constraint quote_request_items_quote_request_id_fkey FOREIGN KEY (quote_request_id) REFERENCES quote_requests(id) ON DELETE CASCADE;
alter table public.supplier_customer_refs add constraint supplier_customer_refs_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;
alter table public.supplier_customer_refs add constraint supplier_customer_refs_customer_location_id_fkey FOREIGN KEY (customer_location_id) REFERENCES customer_locations(id) ON DELETE SET NULL;
alter table public.supplier_customer_refs add constraint supplier_customer_refs_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE;
alter table public.supplier_listing_prices add constraint supplier_listing_prices_run_fkey FOREIGN KEY (import_run_id) REFERENCES catalogue_import_runs(id) ON DELETE SET NULL;
alter table public.supplier_listing_prices add constraint supplier_listing_prices_supplier_listing_id_fkey FOREIGN KEY (supplier_listing_id) REFERENCES supplier_product_listings(id) ON DELETE CASCADE;
alter table public.supplier_locations add constraint supplier_locations_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE;
alter table public.supplier_product_listings add constraint supplier_product_listings_catalogue_product_id_fkey FOREIGN KEY (catalogue_product_id) REFERENCES catalogue_products(id) ON DELETE RESTRICT;
alter table public.supplier_product_listings add constraint supplier_product_listings_last_run_fkey FOREIGN KEY (last_import_run_id) REFERENCES catalogue_import_runs(id) ON DELETE SET NULL;
alter table public.supplier_product_listings add constraint supplier_product_listings_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT;

-- ============================= INDEXES ===============================
create index if not exists catalogue_conflicts_open_idx ON public.catalogue_conflicts USING btree (status, created_at DESC);
create index if not exists catalogue_conflicts_run_idx ON public.catalogue_conflicts USING btree (import_run_id);
create index if not exists catalogue_import_rows_run_action_idx ON public.catalogue_import_rows USING btree (import_run_id, action);
create unique index if not exists catalogue_import_rows_run_row_uidx ON public.catalogue_import_rows USING btree (import_run_id, source_row);
create index if not exists catalogue_import_rows_run_validation_idx ON public.catalogue_import_rows USING btree (import_run_id, validation_result);
create unique index if not exists catalogue_import_runs_checksum_uidx ON public.catalogue_import_runs USING btree (supplier_id, adapter, file_checksum) WHERE (status = 'committed'::text);
create index if not exists catalogue_import_runs_recent_idx ON public.catalogue_import_runs USING btree (created_at DESC);
create index if not exists catalogue_import_runs_status_idx ON public.catalogue_import_runs USING btree (status);
create index if not exists catalogue_products_brand_idx ON public.catalogue_products USING btree (brand);
create index if not exists catalogue_products_ean_idx ON public.catalogue_products USING btree (ean) WHERE (ean IS NOT NULL);
create index if not exists catalogue_products_last_seen_idx ON public.catalogue_products USING btree (last_seen_at DESC);
create index if not exists catalogue_products_mfr_code_idx ON public.catalogue_products USING btree (manufacturer_product_code) WHERE (manufacturer_product_code IS NOT NULL);
create index if not exists catalogue_products_review_idx ON public.catalogue_products USING btree (review_required) WHERE (review_required = true);
create index if not exists catalogue_products_size_idx ON public.catalogue_products USING btree (width_mm, aspect_ratio, rim_inch, season);
create unique index if not exists catalogue_products_validated_ean_uidx ON public.catalogue_products USING btree (ean) WHERE ((ean IS NOT NULL) AND (ean_status = ANY (ARRAY['valid'::text, 'recovered_leading_zero'::text])));
create index if not exists client_offer_requests_company_name_idx ON public.client_offer_requests USING btree (company_name);
create index if not exists client_offer_requests_contact_value_idx ON public.client_offer_requests USING btree (contact_value);
create index if not exists client_offer_requests_created_at_idx ON public.client_offer_requests USING btree (created_at DESC);
create index if not exists client_offer_requests_request_number_idx ON public.client_offer_requests USING btree (request_number);
create index if not exists client_offer_requests_status_idx ON public.client_offer_requests USING btree (status);
create index if not exists client_offer_requests_tyres_gin_idx ON public.client_offer_requests USING gin (tyres);
create index if not exists customer_locations_city_idx ON public.customer_locations USING btree (lower(city));
create index if not exists customer_locations_customer_idx ON public.customer_locations USING btree (customer_id);
create index if not exists customers_fiscal_code_idx ON public.customers USING btree (fiscal_code);
create index if not exists customers_name_idx ON public.customers USING btree (lower(name));
create index if not exists customers_vat_idx ON public.customers USING btree (vat_number);
create index if not exists document_charges_order_idx ON public.document_charges USING btree (order_id);
create index if not exists drivers_active_idx ON public.drivers USING btree (active);
create unique index if not exists drivers_auth_user_id_key ON public.drivers USING btree (auth_user_id) WHERE (auth_user_id IS NOT NULL);
create unique index if not exists drivers_slug_key ON public.drivers USING btree (slug) WHERE (slug IS NOT NULL);
create index if not exists inventory_incidents_open_idx ON public.inventory_incidents USING btree (resolved) WHERE (resolved = false);
create index if not exists inventory_incidents_type_idx ON public.inventory_incidents USING btree (incident_type);
create index if not exists inventory_incidents_unit_idx ON public.inventory_incidents USING btree (inventory_unit_id);
create unique index if not exists inventory_scans_idempotency_key ON public.inventory_scans USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);
create index if not exists inventory_scans_order_idx ON public.inventory_scans USING btree (order_id);
create index if not exists inventory_scans_time_idx ON public.inventory_scans USING btree (scanned_at DESC);
create index if not exists inventory_scans_unit_idx ON public.inventory_scans USING btree (inventory_unit_id);
create index if not exists inventory_units_current_zone_idx ON public.inventory_units USING btree (current_zone_id);
create index if not exists inventory_units_item_status_idx ON public.inventory_units USING btree (order_item_id, status);
create index if not exists inventory_units_order_idx ON public.inventory_units USING btree (order_id);
create index if not exists inventory_units_order_item_idx ON public.inventory_units USING btree (order_item_id);
create index if not exists inventory_units_order_status_idx ON public.inventory_units USING btree (order_id, status);
create index if not exists inventory_units_qr_idx ON public.inventory_units USING btree (qr_token);
create index if not exists inventory_units_status_idx ON public.inventory_units USING btree (status);
create index if not exists order_documents_created_at_idx ON public.order_documents USING btree (created_at DESC);
create index if not exists order_documents_order_idx ON public.order_documents USING btree (order_id);
create index if not exists order_items_brand_idx ON public.order_items USING btree (lower(brand));
create index if not exists order_items_order_idx ON public.order_items USING btree (order_id);
create index if not exists order_items_physical_idx ON public.order_items USING btree (order_id, is_physical);
create index if not exists order_items_supplier_sku_idx ON public.order_items USING btree (supplier_sku);
create index if not exists order_items_tyre_size_idx ON public.order_items USING btree (width, aspect_ratio, rim_diameter);
create index if not exists order_status_history_order_idx ON public.order_status_history USING btree (order_id);
create index if not exists order_status_history_time_idx ON public.order_status_history USING btree (changed_at DESC);
create index if not exists orders_assigned_zone_idx ON public.orders USING btree (assigned_zone_id);
create index if not exists orders_customer_idx ON public.orders USING btree (customer_id);
create index if not exists orders_customer_location_idx ON public.orders USING btree (customer_location_id);
create index if not exists orders_document_date_idx ON public.orders USING btree (document_date);
create index if not exists orders_driver_idx ON public.orders USING btree (driver_id);
create index if not exists orders_fingerprint_idx ON public.orders USING btree (fingerprint) WHERE (fingerprint IS NOT NULL);
create index if not exists orders_planned_delivery_date_idx ON public.orders USING btree (planned_delivery_date);
create index if not exists orders_source_hash_idx ON public.orders USING btree (source_hash) WHERE (source_hash IS NOT NULL);
create index if not exists orders_status_idx ON public.orders USING btree (status);
create unique index if not exists orders_supplier_doc_number_key ON public.orders USING btree (supplier_id, normalized_document_number) WHERE (normalized_document_number IS NOT NULL);
create unique index if not exists orders_supplier_document_unique ON public.orders USING btree (supplier_id, supplier_document_number) WHERE (supplier_document_number IS NOT NULL);
create index if not exists orders_supplier_idx ON public.orders USING btree (supplier_id);
create index if not exists orders_vehicle_idx ON public.orders USING btree (vehicle_id);
create index if not exists orders_vehicle_sequence_idx ON public.orders USING btree (vehicle_id, delivery_sequence);
create unique index if not exists print_jobs_idempotency_key ON public.print_jobs USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);
create unique index if not exists print_jobs_open_unit_key ON public.print_jobs USING btree (inventory_unit_id) WHERE ((inventory_unit_id IS NOT NULL) AND (status = ANY (ARRAY['pending'::text, 'processing'::text])));
create index if not exists print_jobs_order_idx ON public.print_jobs USING btree (order_id);
create index if not exists print_jobs_status_created_idx ON public.print_jobs USING btree (status, created_at);
create index if not exists print_jobs_status_idx ON public.print_jobs USING btree (status);
create index if not exists product_identifiers_lookup_idx ON public.product_identifiers USING btree (normalized_value, identifier_type);
create unique index if not exists product_identifiers_unique_idx ON public.product_identifiers USING btree (catalogue_product_id, identifier_type, normalized_value, COALESCE(supplier_id, '00000000-0000-0000-0000-000000000000'::uuid));
create index if not exists quote_request_events_request_idx ON public.quote_request_events USING btree (quote_request_id, created_at DESC);
create index if not exists quote_request_events_type_time_idx ON public.quote_request_events USING btree (event_type, created_at DESC);
create index if not exists quote_request_items_request_idx ON public.quote_request_items USING btree (quote_request_id, sort_order);
create index if not exists quote_requests_company_lower_idx ON public.quote_requests USING btree (lower(company_name) text_pattern_ops);
create index if not exists quote_requests_created_at_idx ON public.quote_requests USING btree (created_at DESC);
create index if not exists quote_requests_email_lower_idx ON public.quote_requests USING btree (lower(contact_email) text_pattern_ops);
create unique index if not exists quote_requests_idempotency_key_idx ON public.quote_requests USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);
create index if not exists quote_requests_notification_status_idx ON public.quote_requests USING btree (notification_status);
create unique index if not exists quote_requests_public_reference_idx ON public.quote_requests USING btree (public_reference);
create index if not exists quote_requests_request_number_idx ON public.quote_requests USING btree (request_number);
create index if not exists quote_requests_status_created_idx ON public.quote_requests USING btree (status, created_at DESC);
create index if not exists quote_requests_status_idx ON public.quote_requests USING btree (status);
create index if not exists supplier_listing_prices_listing_idx ON public.supplier_listing_prices USING btree (supplier_listing_id, observed_at DESC);
create index if not exists supplier_locations_supplier_idx ON public.supplier_locations USING btree (supplier_id);
create index if not exists supplier_product_listings_last_seen_idx ON public.supplier_product_listings USING btree (supplier_id, last_seen_at DESC);
create index if not exists supplier_product_listings_product_idx ON public.supplier_product_listings USING btree (catalogue_product_id);
create index if not exists supplier_product_listings_supplier_active_idx ON public.supplier_product_listings USING btree (supplier_id, active);
create unique index if not exists supplier_product_listings_supplier_article_uidx ON public.supplier_product_listings USING btree (supplier_id, supplier_article_id);
create index if not exists suppliers_name_idx ON public.suppliers USING btree (lower(name));
create index if not exists suppliers_vat_idx ON public.suppliers USING btree (vat_number);
create index if not exists vehicles_active_idx ON public.vehicles USING btree (active);
create index if not exists vehicles_display_order_idx ON public.vehicles USING btree (display_order);
create unique index if not exists vehicles_slug_key ON public.vehicles USING btree (slug) WHERE (slug IS NOT NULL);

-- ============================= TRIGGERS ==============================
drop trigger if exists app_settings_set_updated_at on public.app_settings;
CREATE TRIGGER app_settings_set_updated_at BEFORE UPDATE ON public.app_settings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists catalogue_conflicts_set_updated_at on public.catalogue_conflicts;
CREATE TRIGGER catalogue_conflicts_set_updated_at BEFORE UPDATE ON public.catalogue_conflicts FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists catalogue_import_runs_set_updated_at on public.catalogue_import_runs;
CREATE TRIGGER catalogue_import_runs_set_updated_at BEFORE UPDATE ON public.catalogue_import_runs FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists catalogue_products_set_updated_at on public.catalogue_products;
CREATE TRIGGER catalogue_products_set_updated_at BEFORE UPDATE ON public.catalogue_products FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists client_offer_requests_set_updated_at on public.client_offer_requests;
CREATE TRIGGER client_offer_requests_set_updated_at BEFORE UPDATE ON public.client_offer_requests FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists customer_locations_set_updated_at on public.customer_locations;
CREATE TRIGGER customer_locations_set_updated_at BEFORE UPDATE ON public.customer_locations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists customers_set_updated_at on public.customers;
CREATE TRIGGER customers_set_updated_at BEFORE UPDATE ON public.customers FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists drivers_set_updated_at on public.drivers;
CREATE TRIGGER drivers_set_updated_at BEFORE UPDATE ON public.drivers FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists inventory_incidents_set_updated_at on public.inventory_incidents;
CREATE TRIGGER inventory_incidents_set_updated_at BEFORE UPDATE ON public.inventory_incidents FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists inventory_units_set_updated_at on public.inventory_units;
CREATE TRIGGER inventory_units_set_updated_at BEFORE UPDATE ON public.inventory_units FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists order_documents_set_updated_at on public.order_documents;
CREATE TRIGGER order_documents_set_updated_at BEFORE UPDATE ON public.order_documents FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists order_items_set_updated_at on public.order_items;
CREATE TRIGGER order_items_set_updated_at BEFORE UPDATE ON public.order_items FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists orders_set_updated_at on public.orders;
CREATE TRIGGER orders_set_updated_at BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists print_jobs_set_updated_at on public.print_jobs;
CREATE TRIGGER print_jobs_set_updated_at BEFORE UPDATE ON public.print_jobs FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists quote_requests_set_updated_at on public.quote_requests;
CREATE TRIGGER quote_requests_set_updated_at BEFORE UPDATE ON public.quote_requests FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists supplier_locations_set_updated_at on public.supplier_locations;
CREATE TRIGGER supplier_locations_set_updated_at BEFORE UPDATE ON public.supplier_locations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists supplier_product_listings_set_updated_at on public.supplier_product_listings;
CREATE TRIGGER supplier_product_listings_set_updated_at BEFORE UPDATE ON public.supplier_product_listings FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists suppliers_set_updated_at on public.suppliers;
CREATE TRIGGER suppliers_set_updated_at BEFORE UPDATE ON public.suppliers FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists vehicles_set_updated_at on public.vehicles;
CREATE TRIGGER vehicles_set_updated_at BEFORE UPDATE ON public.vehicles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists warehouse_zones_set_updated_at on public.warehouse_zones;
CREATE TRIGGER warehouse_zones_set_updated_at BEFORE UPDATE ON public.warehouse_zones FOR EACH ROW EXECUTE FUNCTION set_updated_at();
drop trigger if exists orders_broadcast_change on public.orders;
CREATE TRIGGER orders_broadcast_change AFTER INSERT OR UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION gorush_broadcast_order_change();
drop trigger if exists quote_requests_broadcast_change on public.quote_requests;
CREATE TRIGGER quote_requests_broadcast_change AFTER INSERT OR UPDATE ON public.quote_requests FOR EACH ROW EXECUTE FUNCTION gorush_broadcast_quote_request_change();
drop trigger if exists vehicles_broadcast_change on public.vehicles;
CREATE TRIGGER vehicles_broadcast_change AFTER INSERT OR UPDATE ON public.vehicles FOR EACH ROW EXECUTE FUNCTION gorush_broadcast_vehicle_change();

-- ======================= ROW LEVEL SECURITY ==========================
-- RLS is enabled on every table with ZERO policies: a deliberate
-- deny-by-default posture. Only the service-role key reaches these
-- tables. Do NOT 'fix' this by adding permissive policies.
alter table public.app_settings enable row level security;
alter table public.catalogue_conflicts enable row level security;
alter table public.catalogue_import_rows enable row level security;
alter table public.catalogue_import_runs enable row level security;
alter table public.catalogue_products enable row level security;
alter table public.client_offer_requests enable row level security;
alter table public.customer_locations enable row level security;
alter table public.customers enable row level security;
alter table public.document_charges enable row level security;
alter table public.drivers enable row level security;
alter table public.geocode_cache enable row level security;
alter table public.inventory_incidents enable row level security;
alter table public.inventory_scans enable row level security;
alter table public.inventory_units enable row level security;
alter table public.order_documents enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_history enable row level security;
alter table public.orders enable row level security;
alter table public.print_jobs enable row level security;
alter table public.product_identifiers enable row level security;
alter table public.quote_request_events enable row level security;
alter table public.quote_request_items enable row level security;
alter table public.quote_request_reference_counter enable row level security;
alter table public.quote_request_webhook_events enable row level security;
alter table public.quote_requests enable row level security;
alter table public.supplier_customer_refs enable row level security;
alter table public.supplier_listing_prices enable row level security;
alter table public.supplier_locations enable row level security;
alter table public.supplier_product_listings enable row level security;
alter table public.suppliers enable row level security;
alter table public.vehicles enable row level security;
alter table public.warehouse_zones enable row level security;

-- ============================= COMMENTS ==============================
comment on table public.catalogue_conflicts is 'Cases the importer deliberately refused to resolve. Nothing here is ever settled by picking an arbitrary value - a human decides, or it stays open.';
comment on table public.catalogue_import_rows is 'Staging + audit for every source row of an import. raw_payload is the untouched source and is never overwritten.';
comment on table public.catalogue_import_runs is 'One uploaded supplier catalogue file. status = ''committed'' is the ONLY state that means the data landed; anything else is in flight or failed.';
comment on table public.catalogue_products is 'One normalised tyre SKU. Canonical specifications only - no supplier price, no stock, no physical unit. Never deleted because a supplier file stopped listing it.';
comment on table public.product_identifiers is 'Every code that resolves to a catalogue product - EAN/GTIN, manufacturer code, supplier article code. The warehouse barcode scanner queries normalized_value here.';
comment on table public.quote_request_reference_counter is 'Per-day counter backing quote_requests.public_reference (GR-YYMMDD-NNNN). One row per calendar day, Europe/Rome.';
comment on table public.supplier_listing_prices is 'Supplier purchase price and stock, one row per observation. SUPPLIER COST DATA - must never be reachable from a customer-facing query. Separated from catalogue_products so a price refresh cannot rewrite specifications and a product query cannot leak a cost.';
comment on table public.supplier_product_listings is 'One supplier''s listing of one catalogue product. Two listings may share a product (new stock vs old DOT). Marked inactive only after a COMPLETE catalogue snapshot omits it - never after a partial file.';
comment on column public.catalogue_import_runs.import_mode is 'complete = the supplier''s whole catalogue (may propose deactivations); partial / manual_correction = must never deactivate anything.';
comment on column public.catalogue_products.scan_ready is 'True only when the EAN passed GS1 check-digit validation and may be trusted for warehouse barcode matching.';
comment on column public.catalogue_products.weight_category is 'Supplier weight bucket as shipped (ISB ''1''..''4''). NOT kilograms - see weight_kg.';
comment on column public.inventory_scans.stand_code is 'DEPRECATED: stand/stativ allocation was removed from the active product. Historical value only — no active application code reads or writes this column.';
comment on column public.inventory_units.last_stand_code is 'DEPRECATED: stand/stativ allocation was removed from the active product. Historical value only — no active application code reads or writes this column.';
comment on column public.orders.stand_code is 'DEPRECATED: stand/stativ allocation was removed from the active product. Historical value only — no active application code reads or writes this column.';
comment on column public.quote_requests.delivery_preference is 'Fastest delivery requested across the items (''48h'' or ''7d''), denormalised at insert time so the admin list can show and filter on it without joining items.';
comment on column public.quote_requests.notes is 'Optional free-text note from the customer ("Note aggiuntive"). Never interpreted, only displayed and exported.';
comment on column public.quote_requests.notification_email_sent is 'LEGACY (superseded 2026-08-27) by notification_status. Kept in sync by the application so nothing that still reads it breaks.';
comment on column public.quote_requests.request_number is 'LEGACY (superseded 2026-08-27) by public_reference. Retained so existing rows and any external reference to GR-1000-style numbers still resolve. Not shown in the UI.';
