-- ============================================================================
-- Quote requests ("Richiedi un'offerta") — structured, multi-item quote flow
-- ============================================================================
-- Additive only, same posture as every prior migration in this project.
--
-- RELATIONSHIP TO public.client_offer_requests (20260804000000):
-- That table stays exactly as it is and keeps serving /get-offer. It models
-- one request as a JSONB array of TYRES ONLY, with a single request-level
-- delivery preference and a unified contact_value/contact_type column. The
-- new flow needs things that shape structurally cannot hold:
--   * non-tyre items ("Altro prodotto") with a free-text description
--   * a delivery requirement PER ITEM, not per request
--   * a per-item brand preference (best price vs. a named brand)
--   * a required e-mail plus an OPTIONAL WhatsApp number as separate fields
-- Widening the JSONB blob would have meant breaking the existing form's
-- CHECK constraints and its live rows, so this is a new, normalised pair of
-- tables alongside it rather than a rewrite of a working system.
--
-- Items live in their own table (not JSONB) because the admin list needs to
-- count them, the Excel export needs to iterate them in a stable order, and
-- per-item constraints are worth enforcing in the database.
-- ============================================================================

create extension if not exists pgcrypto;

-- Human-readable request numbers: GR-1000, GR-1001, ... Starting at 1000
-- keeps them four digits from day one (the spec's example is GR-1052) and
-- can never collide with client_offer_requests' 'GR-{year}-{000000}' form,
-- which always carries a year segment.
create sequence if not exists public.quote_request_number_seq start 1000;

-- ---------------------------------------------------------------------------
-- quote_requests
-- ---------------------------------------------------------------------------
create table if not exists public.quote_requests (
  id uuid primary key default gen_random_uuid(),

  -- Generated by the sequence default, so the number is assigned inside the
  -- same transaction as the insert and can never be duplicated by two
  -- concurrent submissions. Never generated client-side.
  request_number text not null unique
    default ('GR-' || nextval('public.quote_request_number_seq')::text),

  company_name text not null check (length(btrim(company_name)) > 0),
  contact_email text not null check (length(btrim(contact_email)) > 0),
  whatsapp text,

  language text not null default 'it' check (language in ('it', 'en')),

  status text not null default 'new' check (
    status in ('new', 'in_progress', 'offer_sent')
  ),

  -- The e-mail is a notification, never the system of record: these columns
  -- record whether it worked WITHOUT the row's existence depending on it.
  notification_email_sent boolean not null default false,
  notification_email_error text,
  notification_email_sent_at timestamptz,

  -- Guards against a double-submit creating two requests. Nullable so a
  -- payload without one still inserts; unique when present (partial index
  -- below).
  idempotency_key text,

  source text not null default 'web',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- quote_request_items
-- ---------------------------------------------------------------------------
create table if not exists public.quote_request_items (
  id uuid primary key default gen_random_uuid(),
  quote_request_id uuid not null
    references public.quote_requests(id) on delete cascade,

  product_type text not null check (product_type in ('tyre', 'other')),

  -- Free text for 'other' items ("Valvole TR414"); null for tyres.
  description text,

  -- Stored as real numbers, never as a "205/55 R16" display string, so the
  -- data stays queryable and the UI owns formatting.
  width integer check (width is null or (width between 100 and 500)),
  profile integer check (profile is null or (profile between 20 and 100)),
  rim integer check (rim is null or (rim between 10 and 30)),

  load_speed_index text,

  quantity integer not null check (quantity > 0 and quantity <= 1000),

  preference_type text check (
    preference_type is null or preference_type in ('best_price', 'specific_brand')
  ),
  preferred_brand text,

  -- Enum-style stable values; the UI renders localized labels. Adding '48h'
  -- later is a one-line constraint change, no restructuring.
  delivery_speed text not null check (delivery_speed in ('24h', '7d')),

  sort_order integer not null default 0,
  created_at timestamptz not null default now(),

  -- --- integrity: the shape must match the product type ---------------
  constraint quote_request_items_tyre_dimensions check (
    product_type <> 'tyre'
    or (width is not null and profile is not null and rim is not null)
  ),
  constraint quote_request_items_other_description check (
    product_type <> 'other'
    or (description is not null and length(btrim(description)) > 0)
  ),
  -- A named-brand preference without a brand is meaningless.
  constraint quote_request_items_brand_present check (
    preference_type is distinct from 'specific_brand'
    or (preferred_brand is not null and length(btrim(preferred_brand)) > 0)
  )
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
create index if not exists quote_requests_created_at_idx
  on public.quote_requests (created_at desc);
create index if not exists quote_requests_status_idx
  on public.quote_requests (status);
create index if not exists quote_requests_request_number_idx
  on public.quote_requests (request_number);
create unique index if not exists quote_requests_idempotency_key_idx
  on public.quote_requests (idempotency_key)
  where idempotency_key is not null;

create index if not exists quote_request_items_request_idx
  on public.quote_request_items (quote_request_id, sort_order);

-- ---------------------------------------------------------------------------
-- updated_at — reuse the project's existing trigger function
-- ---------------------------------------------------------------------------
drop trigger if exists quote_requests_set_updated_at on public.quote_requests;
create trigger quote_requests_set_updated_at
  before update on public.quote_requests
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Row Level Security — RLS ON with NO policies, matching every other table
-- in this project. The anon/publishable key can neither read nor write these
-- rows; all access goes through server-side code holding the service-role
-- key. That is what stops a public visitor listing customer e-mail addresses
-- and WhatsApp numbers.
-- ---------------------------------------------------------------------------
alter table public.quote_requests enable row level security;
alter table public.quote_request_items enable row level security;

-- ---------------------------------------------------------------------------
-- gorush_create_quote_request — request + every item, atomically
-- ---------------------------------------------------------------------------
-- A plpgsql function body runs inside a single transaction, so either the
-- request and ALL of its items exist, or none of them do. This is what
-- prevents the "request saved, item 2 failed, half a request left behind"
-- failure mode.
--
-- Idempotency: if a row with the same idempotency_key already exists, the
-- existing request is returned untouched instead of a second one being
-- created — a double-tapped submit button can never produce two requests.
--
-- SECURITY INVOKER on purpose (same posture as every RPC here): Postgres
-- grants EXECUTE to PUBLIC by default, so SECURITY DEFINER would hand the
-- anon key a write path straight through RLS.
create or replace function public.gorush_create_quote_request(payload jsonb)
returns jsonb
language plpgsql
as $$
declare
  v_request_id uuid;
  v_request_number text;
  v_created_at timestamptz;
  v_idempotency_key text := nullif(btrim(coalesce(payload->>'idempotency_key', '')), '');
  v_item jsonb;
  v_index integer := 0;
  v_item_count integer := 0;
begin
  if payload is null then
    raise exception 'MISSING_PAYLOAD';
  end if;

  -- Replay of an already-accepted submission: return the original.
  if v_idempotency_key is not null then
    select id, request_number, created_at
      into v_request_id, v_request_number, v_created_at
      from public.quote_requests
     where idempotency_key = v_idempotency_key
     limit 1;

    if v_request_id is not null then
      select count(*) into v_item_count
        from public.quote_request_items
       where quote_request_id = v_request_id;

      return jsonb_build_object(
        'request_id', v_request_id,
        'request_number', v_request_number,
        'item_count', v_item_count,
        'created_at', v_created_at,
        'replayed', true
      );
    end if;
  end if;

  if jsonb_array_length(coalesce(payload->'items', '[]'::jsonb)) = 0 then
    raise exception 'NO_ITEMS';
  end if;

  insert into public.quote_requests (
    company_name, contact_email, whatsapp, language, idempotency_key, source
  )
  values (
    btrim(payload->>'company_name'),
    btrim(payload->>'contact_email'),
    nullif(btrim(coalesce(payload->>'whatsapp', '')), ''),
    coalesce(nullif(payload->>'language', ''), 'it'),
    v_idempotency_key,
    coalesce(nullif(payload->>'source', ''), 'web')
  )
  returning id, request_number, created_at
       into v_request_id, v_request_number, v_created_at;

  for v_item in select * from jsonb_array_elements(payload->'items')
  loop
    insert into public.quote_request_items (
      quote_request_id, product_type, description,
      width, profile, rim, load_speed_index,
      quantity, preference_type, preferred_brand, delivery_speed, sort_order
    )
    values (
      v_request_id,
      v_item->>'product_type',
      nullif(btrim(coalesce(v_item->>'description', '')), ''),
      nullif(v_item->>'width', '')::integer,
      nullif(v_item->>'profile', '')::integer,
      nullif(v_item->>'rim', '')::integer,
      nullif(btrim(coalesce(v_item->>'load_speed_index', '')), ''),
      coalesce(nullif(v_item->>'quantity', '')::integer, 1),
      nullif(v_item->>'preference_type', ''),
      nullif(btrim(coalesce(v_item->>'preferred_brand', '')), ''),
      v_item->>'delivery_speed',
      v_index
    );
    v_index := v_index + 1;
  end loop;

  return jsonb_build_object(
    'request_id', v_request_id,
    'request_number', v_request_number,
    'item_count', v_index,
    'created_at', v_created_at,
    'replayed', false
  );
end;
$$;

do $$
begin
  begin
    execute 'revoke all on function public.gorush_create_quote_request(jsonb) from anon, authenticated';
  exception when undefined_object then null;
  end;
end;
$$;
